const COMMANDS: &[&str] = &[
    "activate",
    "validate_key",
    "validate",
    "deactivate",
    "deactivate_key",
    "heartbeat",
    "heartbeat_key",
    "get_status",
    "get_client_status",
    "is_online",
    "get_fingerprint",
    "restore_license",
    "health",
    "check_entitlement",
    "get_entitlements",
    "has_entitlement",
    "get_license",
    "get_state",
    "get_admin_snapshot",
    "get_latest_release",
    "list_releases",
    "generate_download_token",
    "generate_offline_token",
    "verify_offline_token",
    "checkout_machine_file",
    "fetch_signing_key",
    "sync_offline_assets",
    "verify_machine_file",
    "reset",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
